import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import FeedbackHeader from '../components/FeedbackHeader'
import { useGlobalContext } from '../context/GlobalContext'
import Feedback from '../components/Feedback'

export default function Home() {
  const { feedbackData } = useGlobalContext()
  const compareUpvotes = (itemA, itemB) => {
    if (itemA.upvotes < itemB.upvotes) {
      return 1
    } else if (itemA.upvotes === itemB.upvotes) {
      return 0
    } else return -1
  }
  return (
    <div className='bg-indigo-100 min-h-screen overflow-x-hidden'>
      <Head>
        <title>Invoice App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Header />
        <div className='p-4 lg:w-4/5 lg:ml-auto relative lg:mt-8'>
          <FeedbackHeader />
          <div className='mt-14 sm:mt-20 sm:mx-4'>
            {feedbackData.productRequests
              .sort(compareUpvotes)
              .map((request) => {
                return <Feedback key={request.id} {...request} />
              })}
          </div>
        </div>
      </div>
    </div>
  )
}
